"""update mission

Revision ID: 4ce3f2485de1
Revises: 981c5ced23f1
Create Date: 2026-07-22 20:42:50.714375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce3f2485de1'
down_revision: Union[str, Sequence[str], None] = '981c5ced23f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_mission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_url', sa.Text(), nullable=False),
    sa.Column('user_name', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('download_url', sa.Text(), nullable=True),
    sa.Column('headers', sa.Text(), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_mission_page_url'), 'download_mission', ['page_url'], unique=False)
    op.create_index(op.f('ix_download_mission_status'), 'download_mission', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_download_mission_status'), table_name='download_mission')
    op.drop_index(op.f('ix_download_mission_page_url'), table_name='download_mission')
    op.drop_table('download_mission')
    # ### end Alembic commands ###
