"""update mission

Revision ID: 981c5ced23f1
Revises: 
Create Date: 2026-07-22 20:38:51.568513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '981c5ced23f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_download_mission_download_url'), table_name='download_mission')
    op.drop_index(op.f('ix_download_mission_page_url'), table_name='download_mission')
    op.drop_index(op.f('ix_download_mission_status'), table_name='download_mission')
    op.drop_table('download_mission')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_mission',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('page_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('download_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('headers', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('download_mission_pkey'))
    )
    op.create_index(op.f('ix_download_mission_status'), 'download_mission', ['status'], unique=False)
    op.create_index(op.f('ix_download_mission_page_url'), 'download_mission', ['page_url'], unique=False)
    op.create_index(op.f('ix_download_mission_download_url'), 'download_mission', ['download_url'], unique=False)
    # ### end Alembic commands ###
